name: Clippy check

on:
  push:
    branches:
      - next
    paths:
      - '.github/workflows/clippy.yml'
      - 'userspace/ksud_magic/**'
      - 'userspace/ksud_overlayfs/**'
  pull_request:
    branches:
      - next
    paths:
      - '.github/workflows/clippy.yml'
      - 'userspace/ksud_magic/**'
      - 'userspace/ksud_overlayfs/**'

env:
  RUSTFLAGS: '-Dwarnings'

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross --rev 66845c1

      - name: Run clippy
        run: |
          cross clippy --manifest-path userspace/ksud_magic/Cargo.toml --target aarch64-linux-android --release
          cross clippy --manifest-path userspace/ksud_magic/Cargo.toml --target x86_64-linux-android --release
          cross clippy --manifest-path userspace/ksud_overlayfs/Cargo.toml --target aarch64-linux-android --release
          cross clippy --manifest-path userspace/ksud_overlayfs/Cargo.toml --target x86_64-linux-android --release